<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Backend Language Lines
    |--------------------------------------------------------------------------
    |
    | Backend translation.
    |
    */
    // framework
    'license' => 'Licence',
    'framework' => 'Framework',
    'sowfware_category' => 'Software Type',
    'sowfware_category_var' => 'App Backend',
    'license_var' => 'Software Usage',
    'specialty' => 'specialty',
    'specialty_var' => 'Corporate Portal',
    'code' => 'Code #',
    'code_var' => 'Inno_amazing_2016_v.2.0_p1',
    'date_of_issue' => 'Issue Date',
    'date_of_issue_var' => '01-02-2016',
    'copywite' => 'Copywrite',
    'copywite_var' => '© 2016 Innoflame Co.',
    'last_update' => 'Last Update',
    'last_update_var' => 'none',
    //Dashboard
    'welcome_site' => 'Welcome to Backend',
    'sites_total_visits' => 'Sites total visits',
    'sites_web_visits' => 'Sites web visits',
    'sites_android_visits' => 'Sites android visits',
    'sites_ios_visits' => 'Sites ios visits',
    'news_total_visits' => 'News total visits',
    'news_web_visits' => 'News web visits',
    'news_android_visits' => 'News android visits',
    'news_ios_visits' => 'News ios visits',
    'counter' => 'Counter',
    'inno_thanks' => 'thank you for using Inno Amazing',
    //users
    'user' => 'User',
    'users' => 'Users',
    'list_users' => 'list users ',
    'password_confirmation' => 'Password confirmation',
    'role' => 'Role',
    'not_active' => 'Not active',
    'blocked' => 'Blocked',
    'account_settings' => 'Account settings',
    'my_profile' => 'My profile',
    'visitor' => 'Visitor',
    // general
    'project_name' => 'Corporate Portal',
    'control_panel' => 'Control Panel',
    'dashboard' => 'Dashboard',
    'create' => 'Create',
    'close' => 'Close',
    'settings' => 'Settings',
    'smtp_settings' => 'Smtp settings',
    'see_all' => 'See all',
    'logout' => 'Logout',
    'remember_me' => 'Remember me',
    'login' => 'Login',
    'password' => 'Password',
    'email' => 'Email',
    'system_admin' => 'System admin',
    'delete_confirmation' => 'Delete confirmation',
    'bulk_delete_confirmation' => 'Bulk delete confirmation',
    'confirm_delete_msg' => 'Are you sure you want to delete',
    'operations' => 'Operations',
    'no_results_found' => 'No results found',
    'total' => 'Total',
    'status' => 'Status',
    'the_following' => 'the following',
    'published' => 'Published',
    'unpublished' => 'Unpublished',
    'bulk_publish' => 'Bulk Publish',
    'bulk_unpublish' => 'Bulk Unpublish',
    'filter' => 'Filter',
    'add_new' => 'Add new',
    'create_content' => 'create content',
    'no_data_added_before' => 'No data added before',
    'back' => 'back',
    'add_new_after_save' => 'Add new after save',
    'back_after_update' => 'Back after update',
    'select' => 'Select',
    'languages' => 'Languages',
    'select_languages_you_need_to_delete' => 'Select language You want to delete item from it:',
    'social_published' => 'Social media published',
    'teaser' => 'Teaser',
    'location' => 'Location',
    'site_search' => 'Site search',
    'nothing' => 'Nothing',
    // system messages
    'saved_successfully' => 'Saved successfully',
    'updated_successfully' => 'Updated successfully',
    'deleted_successfully' => 'Deleted successfully',
    'nothing_selected' => 'Nothing selected',
    // buttons
    'save' => 'Save',
    'edit' => 'Edit',
    'update' => 'Update',
    'delete' => 'Delete',
    'cancel' => 'Cancel',
    'bulk_delete' => 'Bulk Delete',
    'bulk_active' => 'Bulk Active',
    'bulk_deactivate' => 'Bulk Deactivate',
    'bulk_block' => 'Bulk Block',
    'save_settings' => 'Save settings',
    // media
    'media_manager' => 'Media manager',
    'main_image' => 'Main image',
    'select_image' => 'Select image',
    'upload_new_image' => 'Upload new image',
    'image' => 'Image',
    'max_size' => 'Max size',
    'supported_extantions' => 'Supported extantions',
    'upload' => 'Upload',
    'image_uploaded_successfully' => 'image uploaded successfully',
    // content fileds
    'title' => 'Title',
    'name' => 'Name',
    'description' => 'Description',
    'body' => 'Body',
    'author' => 'Author',
    'created_at' => 'Created at',
    'last_update' => 'Last update',
    'updated_by' => 'Last update by',
    'receive_date' => 'Receive date',
    'link' => 'link',
    // messages & contact us
    'messages' => 'Messages',
    'new_messages' => 'New messages',
    'replied_messages' => 'Replied messages',
    'no_new_messages' => 'no new messages',
    //sections
    'sections' => 'Sections',
    'list_sections' => 'List sections',
    'section' => 'Section',
    'section_name' => 'Section name',
    'section_filter' => 'Section filter',
    // sites
    'list_sites' => 'List sites',
    'site' => 'Site',
    'important_site' => 'Important site',
    'feature_site' => 'Feature site',
    // Tourism services
    'tourism_services' => 'Tourism services',
    '' => '',
    '' => '',
    // Tourism sites
    'tourism_sites' => 'Tourism sites',
    '' => '',
    //News
    'manage_comments' => 'Manage Comments',
    'list_comments' => 'List Comments',
    'code' => 'Code',
    'comments' => 'Comments',
    'comment' => 'Comment',
    'type' => 'Type',
    'content' => 'Content',
    'active' => 'Active',
    'active_comments' => 'Active Comments',
    'confirm_active_comments' => 'Confirm The Activation Of Comments',
    'Activation was done successfully' => 'Activation was done successfully',
    'there_is_no_result' => 'There is no result',
    'manage_valbums' => 'Manage Video Albums',
    'list_valbums' => 'List Video Albums',
    'summary' => 'Summary',
    'add_more' => 'Add More',
    'aboutus' => 'About Us',
    'aboutehsaa' => 'About El-Ehsaa',
    'list_banners' => 'List Banners',
    'news' => 'News',
    'list_news' => 'List News',
    'subject' => 'Subject',
    'important_news' => 'Important News',
    'share_on_facebook&twitter' => 'Share on Facebook & Twitter',

    //Banners
    'list_banners' => 'List Banners',
    'banners' => 'Banners',
    'banner' => 'Banner',
    //videos
    'list_videos' => 'List Videos',
    'brief' => 'Brief',
    'valbums' => 'Video Albums',
    'valbum' => 'Video Album',
    'videos' => 'Videos',
    // contact us
    'contact_messages' => 'Contact messages',
    'messages_details' => 'Message details',
    'list_messages' => 'list messages',
    'from' => 'From',
    'from_user' => 'From User',
    'message_subject' => 'Message subject',
    'message' => 'Message',
    'reply' => 'Reply',
    'message_reply' => 'Message reply',
    'send' => 'Send',
    'replied_successfully' => 'Replied successfully',
    'sent_successfully' => 'Sent successfully',
    're' => 'Re',
    'error_sent' => 'message not sent, if the problem happen in many messages, please make revision of Smtp settingsmessage not sent, if the problem happen in many messages, please make revision of Smtp settings',
    //pages
    'list_pages' => 'List Pages',
    'pages' => 'Pages',
    //Important Links
    'list_implinks' => 'List Important Links',
    'implinks' => 'Important Links',
    'implink' => 'Important Link',
    //Contact Us
    'message_details' => 'Message details',
    'mail' => 'E-mail',
    'contacts_info' => 'Contacts Information',
    'phone_numbers' => 'Phone Numbers',
    'list_contacts' => 'List Contacts',
    'gmap' => 'location coordinates',
    'location' => 'Location',
    'Dimension' => 'Dimension',
    'latitude' => 'Latitude',
    'longitude' => 'Longitude',
    'no_results' => 'No results',
    'phone' => 'Phone',
    'Note: You should put the marker at your location' => 'Note: You should put the marker at your location',
    //Complains
    'List Complains Sections' => 'List Complains Sections',
    'Complains Sections' => 'Complains Sections',
    'Sections' => 'Sections',
    'list_Complains Sections' => 'List Complains Sections',
    'List Complains' => 'List Complains',
    'Complains' => 'Complains',
    'complain' => 'Complain',
    'Complain Sections' => 'Complain Sections',
    'Complain details' => 'Complain details',
    'Create Complains Sections' => 'Create Complains Sections',
    'New Complains' => 'New Complains',
    'Replied Complains' => 'Replied Complains',
    //Gallery
    'photo_gallery' => 'Photo gallery',
    'select_images' => 'Select images',
    'upload_new' => 'Upload new',
    //Photo Gallery
    'list_photo_albums' => 'List Photo Albums',
    'photo_album' => 'Photo Album',
    'Photo Gallery' => 'Photo Gallery',
	//Reviews
    'manage_reviews' => 'Manage Reviews',
    'list_reviews' => 'List Reviews',
    'reviews' => 'Reviews',
	//Map Tracks
    'Map Tracks' => 'Map Tracks',
    'GO TO EDIT PAGE' => 'GO TO EDIT PAGE',
    'GO TO ADD PAGE' => 'GO TO ADD PAGE',
    //Events
    'events' => 'Events',
    'list_events' => 'List Events',
    'event' => 'Event',
    //Menu
    'list_menus' => 'List Menus',
    'menu_name' => 'Menu Name',
    'menu_links' => 'Menu Links',
    'menu' => 'Menu',
    'list_links' => 'List Links',
    'collapse_all' => 'Collapse All',
    'expand_all' => 'Expand All',
    'links' => 'Links',
    'delete_confirm' => 'Confirm delete',
    'provide_menu_link' => 'Provide to Menu',
    'menus' => 'Menus',
    'select' => 'select',
    'choose menu' => 'Choose Menu',
    //Events
    'Appointment' => 'Appointment',
    //Products
    'list_products' => 'List Products',
    'products' => 'Products',
    //Services
    'list_services' => 'List Services',
    'services' => 'Services',
    //Main Information
    'Main Info' => 'Main Information',
    'Site Name' => 'Site Name',
    'Keywords' => 'Keywords',
    'logo' => 'Logo',
    'favicon' => 'Favicon',
    'Choose Photo' => 'Choose Photo',
    'Change' => 'Change',
    //Tickets
    'tickets' => 'Tickets',
    'list_tickets' => 'List Tickets',
    'Are you sure to close' => 'Are you sure to close',
    'closed_successfully' => 'Closed Successfully',
    'closed' => 'Closed',
    'opened' => 'Opened',
    //Social Media
    'Social Media' => 'Social Media',
    'facebook' => 'Facebook',
    'twitter' => 'Twitter',
    'gplus' => 'G+',
    'linkedin' => 'Linkedin',
    //frontend
    'Welcome to' => 'Welcome to',
    'Official Website' => 'Official Website',
    'Services' => 'Services',
    'Meet Our Services' => 'Meet Our Services',
    'Events' => 'Events',
    'Our Products' => 'Our Products',
    'Latest News' => 'Latest News',
    'Important Links' => 'Important Links',
    'Recent Pages' => 'Recent Pages',
    'Contacts' => 'Contacts',
    'Copyright' => 'Copyright',
    'All rights reserved' => 'All rights reserved',
    'Created by' => 'Created by',
    'Contact Us' => 'Contact Us',
    'Your Name' => 'Your Name',
    'Your Email' => 'Your Email',
    'Your phone' => 'Your phone',
    'Subject' => 'Subject',
    'Message' => 'Message',
    'submit now' => 'Submit Now',
    'Log In' => 'Log In',
    'submit' => 'Submit',
    'Your password' => 'Your password',
    'Confirm password' => 'Confirm password',
    'Register' => 'Register',
    'Your Profile' => 'Your Profile',
    'Profile' => 'Profile',
    'Log out' => 'Log out',
    'Tickets' => 'Tickets',
    'Details' => 'Details',
    'Create New Ticket' => 'Create New Ticket',
    'You have to login to create ticket' => 'You have to login to create ticket',
    'Address In Arabic' => 'Address In Arabic',
    'Title In Arabic' => 'Title In Arabic',
    // Custom override ** if you need to rename special of used in the top
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    // API
    'not_authorized' => 'Not authorized',
    'comment_is_required' => 'Comment is required',
    'comment_type_validation' => 'Type is required and must be numeric, 1 for Tourist Services && 2 for Tourist sites',
    'comment_content_id_validation' => 'Content id is required or must be numeric',
    'review_is_required' => 'review is required or must be numeric',
    'album_not_found' => 'Album not found',
    'news_not_found' => 'News not found',
    'page_not_found' => 'Page not found',
    'map_not_found' => 'Map not found',
    'download_app' => 'Download app',
    'apple_store' => 'Apple store',
    'google_store' => 'Google store',
    'app_links' => 'App links',
];
